cuts = {
    "-FAKE_TAU_GEN_MATCH-" : "(tree.alltau_gen_match[tree.tau_iso_ind] == 6)",
    "-NJET_0-"             : "(tree.njets == 0)",
    "-NJET_1-"             : "(tree.njets == 1)",
    "-NJET_geq1-"          : "(tree.njets >= 1)",
    "-NJET_geq2-"          : "(tree.njets >= 2)",
    "-1prong0pi0-"         : "(tree.alltau_decay[tree.tau_iso_ind]==0)",
    "-1prong1pi0-"         : "(tree.alltau_decay[tree.tau_iso_ind]==1)",
    "-3prong0pi0-"         : "(tree.alltau_decay[tree.tau_iso_ind]==10)",
    "-3prong1pi0-"         : "(tree.alltau_decay[tree.tau_iso_ind]==11)",
    "-OS-"                 : "(tree.lep_q*tree.alltau_q[tree.tau_iso_ind] < 0)",
    "-SS-"                 : "(tree.lep_q*tree.alltau_q[tree.tau_iso_ind] > 0)",
    "-2L-"                 : "(tree.passesDLVeto > 0.5)",
    "-3L-"                 : "(tree.passes3LVeto > 0.5)",
    "-MT_SR-"              : "(tree.alltau_mt[tree.tau_iso_ind] < 70)",
    "-MT_DR-"              : "(tree.alltau_mt[tree.tau_iso_ind] > 70)",
    "-LepIso-"             : "(tree.lep_iso < 0.15)", 
    "-TauIsoPass-"         : "(tree.alltau_tightDNN[tree.tau_iso_ind]>0.5)",
    "-TauIsoFail-"         : "(tree.alltau_vlooseDNN[tree.tau_iso_ind]>0.5)*(tree.alltau_tightDNN[tree.tau_iso_ind]<0.5)",
    "-Bpt_1-"              : "(tree.bpt_1 < 20)",
}