cuts = {
    "-FAKE_TAU_GEN_MATCH-" : "(tree.alltau_gen_match[tree.tau_iso_ind] == 6)",
    "-NJET_0-"             : "(tree.njets == 0)",
    "-NJET_1-"             : "(tree.njets == 1)",
    "-NJET_g1-"            : "(tree.njets > 1)",
    "-NJET_geq1-"          : "(tree.njets >= 1)",
    "-NJET_geq2-"          : "(tree.njets >= 2)",
    "-1prong0pi0-"         : "(tree.alltau_decay[tree.tau_iso_ind]==0)",
    "-1prong1pi0-"         : "(tree.alltau_decay[tree.tau_iso_ind]==1)",
    "-3prong0pi0-"         : "(tree.alltau_decay[tree.tau_iso_ind]==10)",
    "-3prong1pi0-"         : "(tree.alltau_decay[tree.tau_iso_ind]==11)",
    "-OS-"                 : "(tree.lep_q*tree.alltau_q[tree.tau_iso_ind] < 0)",
    "-SS-"                 : "(tree.lep_q*tree.alltau_q[tree.tau_iso_ind] > 0)",
    "-2L-"                 : "(tree.passesDLVeto > 0.5)",
    "-3L-"                 : "(tree.passes3LVeto > 0.5)",
    "-3Lfail-"             : "(tree.passes3LVeto < 0.5)",
    "-NisoLep_geq1-"       : "(tree.n_iso_lep >= 1)",
    "-Bjet_1-"             : "(tree.bpt_1 >= 20)",
    "-dRlep-"              : "(tree.alltau_dRToLep[tree.tau_iso_ind] > 0.4)",
    "-dRotherlep-"         : "(tree.alltau_dRToOtherLep[tree.tau_iso_ind] > 0.4)",
    "-MT_SR-"              : "(tree.alltau_mt[tree.tau_iso_ind] < 70)", 
    "-MT_DR-"              : "(tree.alltau_mt[tree.tau_iso_ind] > 70)",
    "-MT_DRQCD-"           : "(tree.alltau_mt[tree.tau_iso_ind] < 40)",
    "-LepIso-"             : "(tree.lep_iso < 0.15)", 
    "-LepIso_ttchan-"      : "(tree.lep_iso > 9.000000)", 
    "-LepIsoQCD-"          : "(tree.lep_iso > 0.05)", 
    "-TauIsoPass-"         : "(tree.alltau_tightDNN[tree.tau_iso_ind]>0.5)",
    "-TauIsoFail-"         : "(tree.alltau_vlooseDNN[tree.tau_iso_ind]>0.5)*(tree.alltau_tightDNN[tree.tau_iso_ind]<0.5)",
    "-Bpt_1-"              : "(tree.bpt_1 < 20)",
    "-dRlet3-"             : "(tree.alltau_dRToLep[tree.tau_iso_ind] <= 3.0)",
    "-dRgt3-"              : "(tree.alltau_dRToLep[tree.tau_iso_ind] > 3.0)",
}